### PR TITLE
[WIP] fix/react-frontend

### PR DESCRIPTION
**Pull request by jgwerner**
Signed-off-by: Greg Werner <werner.greg@gmail.com>

#28 #29

### CODE REVIEW

**Comment by jgwerner** [comment]
@jkp85 I need some help understanding what the `TBS_HOST` value should be when the `react-frontend` container is running on the same host as `app-backend` server, using docker-compose. I'm assuming that an incorrect value for TBS_HOST is being added since the error message when navigating to `http://dev.3blades.io/` is:

    Invalid Host header

However, the error could be appearing because of another misconfiguration.

I ran the following configuration options to test:

1. Used Elastic Load Balancer using CNAME record from ELB to dev.3blades.io
2. Used EC2 instance with A record from instance to dev.3blades.io
3. Navigating directly to the OpenResty exposed port works: http://dev.3blades.io:5000/swagger/
4. Doing a `docker exec ...` into the `react-frontend` container to test connectivity to reverse proxy server works with `curl server`
5. Tested connectivity locally using `curl localhost:3000` (other ports were tested for safe measure).

It is important to note that `react-frontend` successfully connects to the backend when running on another instance.

cc/ @roachmd

**Comment by jkp85** [comment]
@jgwerner If you are trying to connect react frontend to app backend via docker compose then I would add `depends_on: server` and connect via `http://server:5000`. This way you will connect directly to server container.

**Comment by jgwerner** [comment]
@jkp85 `depends_on: server` is in the compose yml. Here is what the docker-compose.yml file looks like once the ansible playbook has completed its tasks:

```
version: '2'
services:
  api:
    image: 3blades/app-backend:latest
    command: /srv/env/bin/gunicorn --bind 0.0.0.0:80 --reload --workers 1 --log-level=DEBUG --error-logfile=- --access-logfile=- appdj.wsgi
    volumes:
      - /workspaces:/workspaces
    env_file: env
    depends_on:
      - db
      - cache
      - broker
  celery:
    image: 3blades/app-backend:latest
    command: /srv/env/bin/celery -A appdj worker -l info
    volumes:
      - /workspaces:/workspaces
    env_file: env
    depends_on:
      - db
      - cache
      - broker
    entrypoint: ''
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes_from:
      - container:postgresql-data:rw
  broker:
    image: rabbitmq:alpine
    ports:
      - 5672:5672
  search:
    image: elasticsearch:2-alpine
    ports:
      - 9200:9200
  cache:
    image: redis:alpine
    ports:
      - 6379:6379
  server:
    image: 3blades/openresty:latest
    command: -p '' -c nginx.conf -g 'daemon off;'
    env_file: env
    ports:
      - 5000:80
    depends_on:
      - api
    volumes_from:
      - api
  events:
    image: 3blades/docker-events:latest
    env_file: env
    ports:
      - 8000:8000
  frontend:
    image: 3blades/react-frontend:latest
    env_file: env
    ports:
      - 3000:3000
    depends_on:
      - server
```

This is the resulting env:

```
API_URL=http://server:5000
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_STORAGE_BUCKET_NAME=
AWS_S3_CUSTOM_DOMAIN=
C_ROOT=1
DATABASE_URL=postgres://postgres:@db:5432/postgres
DEBUG=True
DJANGO_SETTINGS_MODULE=appdj.settings.dev
DOCKER_DOMAIN=172.17.0.1:2375
DOCKER_HOST=tcp://172.17.0.1:2375
ELASTICSEARCH_URL=http://search:9200/
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
RABBITMQ_URL=amqp://broker
REDIS_URL=redis://cache:6379/0
RESOURCE_DIR=/workspaces
SECRET_KEY=122d3df3005ef54989a73674f04c9de22343357928853558
SERVER_PORT=8000
SERVER_RESOURCE_DIR=/resources
SITE_ID=
SLACK_KEY=
SLACK_SECRET=
STRIPE_SECRET_KEY=
TBS_HOST=dev.3blades.io
```

**Comment by jkp85** [comment]
@jgwerner `API_URL` should be `http://server` 5000 is port that is exposed, but internally it should be default 80 port.

**Comment by jkp85** [comment]
Scratch that last comment. Frontend is a client app, it should be pointed to public url, so it probably should be `API_URL=https://dev.3blades.io` If this won't work then there is something wrong with other configs. @jgwerner On what address frontend will be?

**Comment by jgwerner** [comment]
@jkp85 http://dev.3blades.io:3000 what we have published now for frontend.

**Comment by jkp85** [comment]
Ok, so `API_URL` should be as I stated above.

**Comment by jgwerner** [comment]
@jkp85 that's right, API_URL is as stated above, value is confirmed in [env file](https://github.com/3Blades/onpremise/pull/30#issuecomment-309749506).

**Pull request merged**
